name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: make ci
